# Date created: 2018-03-14
# Owner: nova Institute (Reg# 1994/002614/08).

warning("update this description")
# ---------------------------------------- #
#' The functions in this script prepare indicator definition tables for the General Household Survey (GHS).
#' Three different definition tables are generated:
#'   1. A table for indicators from 'yes'/'no' response variables (e.g. 'energy_coal_use'), 
#'      called "type 1" indicators. Generated by 'indicDefs_tp1_GHS_hh(...)'.
#'   2. A table for indicators from quantitative variables (e.g. 'energy_coal_consumption_wintercurrentunits),
#'      called "type 2" indicators
#'   3. A table for indicators generated from other indicators (e.g. 'TNNE_COAL_PCOMM_PMONTH_WINTR_SV_GHS2017' which
#'      is generated from 'KG_COAL_PCOALHH_PMONTH_WINTR_SV_GHS2017' and 'KG_COAL_PCOALHH_PMONTH_SUMMR_SV_GHS2017'),
#'      called "type 3" indicators.
#'
#' Custom indicators can also be added to the tables using this script.
#' 
#' Example of use (not run):
#'   source("./global.R")
#'   load(paste(rdadir, "SV_GHS2017.Rda", sep = ""))
#'   
#'   dfIndicDefs_tp1 <- indicDefs_tp1(dfHh = dfHh_SV_GHS2017)
#'   write.xlsx(x = dfIndicDefs_tp1, file = "dfIndicDefs_tp1_GHS.xlsx")
#'   
#'   dfIndicDefs_tp2 <- indicDefs_tp2(dfHh = dfHh_SV_GHS2017)
#'   save(dfIndicDefs_tp2, file = "dfIndicDefs_tp2_GHS.Rda")
#'    
#'   dfIndicDefs_tp3 <- indicDefs_tp3()
#'   assign(x = "dfIndicDefs_tp3_GHS", value = dfIndicDefs_tp3, envir = .GlobalEnv)
#'

# ---------------------------------------- #
#'Generates the indicator definitions/descriptions for type 1 ('yes'/'no' vars) indicators from the household dataset
#'@param datasetNm E.g. 'GHS2017' or 'GHS2016'
# TODO: add custom type 1 indicator definitions to the end of this function

indicDefs_tp1_GHS_hh <- function(dfHh, datasetNm = "GHSXXXX") {
  
  indicTypes1 <- c("n_hhs", "perc_hhs")
  nmsYesNoVars <- names(dfHh)[sapply(X = dfHh, FUN = function(x) {
    return(all(unique(x) %in% c(NA, "yes", "no")) & !all(is.na(x)))
  })]
  
  nmsExcludeVars <- grep(pattern = "contact|feedback|respondent|txt|perception|other|income|medical|container|prevalence|safety|health|waste|formal|informal|mixed|multi|has_rdp|ceiling", 
                         x = nmsYesNoVars, value = TRUE)
  nmsIndicVars <- c(setdiff(nmsYesNoVars, nmsExcludeVars), 
                    "sol_waste_household_collectionfailure_disposal_i_burn_it", 
                    "sol_waste_household_collection",
                    NA_character_)
  nmsFilterVars <- c(grep(pattern = "_use$", x = nmsIndicVars, value = TRUE), NA_character_)
  groupVars <- c(NA_character_, "house_type")
  
  lsOpts <- list(indicTypes1, nmsIndicVars, nmsFilterVars, groupVars)
  dfAllPossIndics <- expand.grid(lsOpts, stringsAsFactors = FALSE)
  names(dfAllPossIndics) <- c("stat", "indicVar", "filters", "groupVar")
  idxx <- which((is.na(dfAllPossIndics$indicVar) & is.na(dfAllPossIndics$groupVar)) |
                  (dfAllPossIndics$indicVar == dfAllPossIndics$filters) |
                  (dfAllPossIndics$indicVar == dfAllPossIndics$groupVar) |
                  (is.na(dfAllPossIndics$indicVar) & !is.na(dfAllPossIndics$filters) & !is.na(dfAllPossIndics$groupVar)))  
  #View(dfAllPossIndics[idxx,])
  dfAllPossIndics <- dfAllPossIndics[-idxx,]
  
  # ------------------- #
  # Add some variables to dfAllPossIndics that we will need to build the 'name' and 'descr' vars
  
  energyCarriers <- c("coal", "charcoal", "wood", "paraffin", "lpg", "electricity", 
                      "solid_fuel", "dirty_fuel", "dung", "solar")
  items <- c(energyCarriers, "waste")
  
  # season
  dfAllPossIndics$season <- NA_character_
  for (seas in c("summer","winter")) {
    idxx <- grep(pattern = seas, x = dfAllPossIndics$indicVar)
    dfAllPossIndics$season[idxx] <- seas
  }
  idxx1 <- grep(pattern = paste(energyCarriers, sep = "|", collapse = "|"), 
                x = dfAllPossIndics$indicVar)
  idxx2 <- which(is.na(dfAllPossIndics$season))
  dfAllPossIndics$season[intersect(idxx1,idxx2)] <- "any_season"
  unique(dfAllPossIndics$indicVar[which(is.na(dfAllPossIndics$season))])
  
  # purpose / use case
  dfAllPossIndics$purpose <- NA_character_
  purposes <- c("heating", "cooking")
  for (purpose in purposes) {
    idxx <- grep(pattern = purpose, x = dfAllPossIndics$indicVar, fixed = TRUE)
    dfAllPossIndics$purpose[idxx] <- purpose
  }
  unique(dfAllPossIndics$indicVar[which(is.na(dfAllPossIndics$purpose))])
  
  # 'item' var
  dfAllPossIndics$item <- NA_character_
  for (item in items) {
    idxx <- grep(pattern = item, x = dfAllPossIndics$indicVar)
    dfAllPossIndics$item[idxx] <- item
  }
  unique(dfAllPossIndics$indicVar[which(is.na(dfAllPossIndics$item))])
  
  # x-using hhs var
  dfAllPossIndics$subset <- NA_character_
  dfAllPossIndics$subset_item <- NA_character_
  for (item in items) {
    idxx <- grep(pattern = item, x = dfAllPossIndics$filters)
    dfAllPossIndics$subset_item[idxx] <- item
  }
  idxx <- which((!is.na(dfAllPossIndics$filters)))
  dfAllPossIndics$subset[idxx] <- sprintf("%s-using", dfAllPossIndics$subset_item[idxx])
  table(dfAllPossIndics$subset_item, exclude = NULL)
  
  # ------------------- #
  # now build the actual 'descr' var
  dfAllPossIndics$descr <- sprintf("%s %s households %s %s %s %s %s. Main place: %s. Dataset: %s.",
                                   ifelse(dfAllPossIndics$stat %in% c("n_hhs"), 
                                          "Number of", "Percentage of"),
                                   ifelse(is.na(dfAllPossIndics$subset), "", dfAllPossIndics$subset),
                                   case_when(dfAllPossIndics$item == "waste" ~ "burning", 
                                             dfAllPossIndics$item %in% energyCarriers ~ "using",
                                             is.na(dfAllPossIndics$item) ~ ""),
                                   ifelse(is.na(dfAllPossIndics$item), "", dfAllPossIndics$item),
                                   ifelse(is.na(dfAllPossIndics$purpose), "", 
                                          sprintf("for %s", dfAllPossIndics$purpose)),
                                   ifelse(is.na(dfAllPossIndics$season), "", 
                                          sprintf("in %s", dfAllPossIndics$season)),
                                   ifelse(is.na(dfAllPossIndics$groupVar), "", 
                                          sprintf(", given by %s", dfAllPossIndics$groupVar)),
                                   "Sharpeville",
                                   datasetNm)
  dfAllPossIndics$descr <- gsub(pattern = "[[:blank:]]{2,}", replacement = " ", x = dfAllPossIndics$descr)
  dfAllPossIndics$descr <- gsub(pattern = "([[:blank:]])([[:punct:]])", replacement = "\\2", x = dfAllPossIndics$descr)
  dfAllPossIndics$descr <- gsub(pattern = "_", replacement = " ", x = dfAllPossIndics$descr, fixed = TRUE)
  
  # ------------------- #          
  # build the 'name' var for dfAllPossIndics
  # N_PRFFNHHS_ELEC_ANYSEAS_SV_GHS2017
  
  idxx <- which(!is.na(dfAllPossIndics$filters))
  dfAllPossIndics$stat2 <- gsub(pattern = "hhs", replacement = "", x = dfAllPossIndics$stat)
  dfAllPossIndics$stat2 <- sprintf("%s%shhs", 
                                   dfAllPossIndics$stat2, 
                                   ifelse(is.na(dfAllPossIndics$subset_item), "", dfAllPossIndics$subset_item))
  unique(dfAllPossIndics$stat2)
  
  dfAllPossIndics$name <- sprintf("%s_%s_%s_%s_%s_SV_%s",
                                  dfAllPossIndics$stat2, 
                                  ifelse(is.na(dfAllPossIndics$item), "", dfAllPossIndics$item),
                                  ifelse(is.na(dfAllPossIndics$season), "", dfAllPossIndics$season),
                                  ifelse(is.na(dfAllPossIndics$purpose), "", dfAllPossIndics$purpose),
                                  ifelse(is.na(dfAllPossIndics$groupVar), "", sprintf("by%s",dfAllPossIndics$groupVar)),
                                  datasetNm)
  
  abbrevs <- c("summer", "summr",
               "winter", "wintr",
               "any_season", "anyseas",
               "solid_fuel", "solidf",
               "dirty_fuel", "dirtyf",
               "heating", "spcheatanyw",
               "electricity", "elec",
               "paraffin", "prffn",
               "solid_fuel", "solidf",
               "dirty_fuel", "dirtyf",
               "house_type", "housetp")
  
  for (i in seq.int(from = 1, to = length(abbrevs) -1, by = 2)) {
    dfAllPossIndics$name <- gsub(pattern = abbrevs[i], replacement = abbrevs[i+1], x = dfAllPossIndics$name, fixed = TRUE)
  }
  
  dfAllPossIndics$name <- gsub(pattern = "_{2,}", replacement = "_", x = dfAllPossIndics$name)
  dfAllPossIndics$name <- toupper(dfAllPossIndics$name)

  ## temporary fix
  warning("TODO: remove this")
  #unique(grep(pattern = "formal|informal|multi|mixed|ceiling|rdp", x = dfAllPossIndics$indicVar, value = TRUE))
  
  idxx <- which(dfAllPossIndics$indicVar == "sol_waste_household_collection")
  if (length(idxx) > 0) {
    dfAllPossIndics$name[idxx] <- gsub(pattern = "WASTE", 
                                       replacement = "SRVCWASTECOLL", 
                                       x = dfAllPossIndics$name[idxx], fixed = TRUE)
    dfAllPossIndics$descr[idxx] <- gsub(pattern = "burning waste", 
                                        replacement = "with access to waste collection services", 
                                        x = dfAllPossIndics$descr[idxx], fixed = TRUE)
  }
  
  length(unique(dfAllPossIndics$name))
  if (length(unique(dfAllPossIndics$name)) < nrow(dfAllPossIndics)) {
    sample(x = unique(dfAllPossIndics$name[duplicated(dfAllPossIndics$name)]), size = 10)
  }
  
  # ------------------- #
  # create the 'unit' var in dfAllPossIndics
  dfAllPossIndics$unit <- case_when(dfAllPossIndics$stat %in% c("n_hhs") ~ "(count)",
                                    dfAllPossIndics$stat %in% c("perc_hhs") ~ "%")
  
  # ------------------- #
  # create the 'indicOpt' var in dfAllPossIndics
  dfAllPossIndics$indicOpt <- NA_character_
  dfAllPossIndics$indicOpt[which(dfAllPossIndics$indicVar %in% nmsYesNoVars)] <- "yes"
  table(dfAllPossIndics$indicOpt, exclude = NULL)
  
  # ------------------- #
  # add a 'comment' var
  dfAllPossIndics$comment <- NA_character_
  
  # ------------------- #
  # finish off the 'filters' var
  dfAllPossIndics$filters <- sprintf("%s == 'yes'",dfAllPossIndics$filters)
  
  # ------------------- #
  # remove the vars from dfAllPossIndics that we no longer need
  dfAllPossIndics <- dfAllPossIndics[,c("name", "unit", "indicVar", "indicOpt", 
                                        "filters", "groupVar", "descr", "comment")]
  
  #TODO:
  # 1. The 'utility' vars have to be translated to purposes.
  # 2. Heater type vars (and similar ones) must be excluded.
  
  return(dfAllPossIndics)
}

indicDefs_tp1_GHS_person <- function() {}

indicDefs_tp1_GHS_structs <- function() {}


